openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
paths:
  /users:
    post:
      summary: Create a new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
                - username
      responses:
        '201':
          description: User created successfully

  /users/{username}:
    get:
      summary: Retrieve details of a specific user
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response

  /groups:
    post:
      summary: Create a new group
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                groupName:
                  type: string
              required:
                - groupName
      responses:
        '201':
          description: Group created successfully

  /groups/{groupname}:
    get:
      summary: Retrieve details of a specific group
      parameters:
        - in: path
          name: groupname
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response

    post:
      summary: Add a member to a group
      parameters:
        - in: path
          name: groupname
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
                - username
      responses:
        '200':
          description: Member added successfully

  /groups/{groupname}/reports:
    get:
      summary: Retrieve reports associated with a specific group
      parameters:
        - in: path
          name: groupname
          required: true
          schema:
            type: string
        - in: query
          name: username
          schema:
            type: string
            nullable: true
      responses:
        '200':
          description: Successful response
  /groups/{groupname}/addMember:
    post:
      summary: Add a member to a group
      parameters:
        - in: path
          name: groupname
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
                - username
      responses:
        '200':
          description: Member added successfully
  /reports:
    get:
      summary: Retrieve a list of reports
      parameters:
        - in: query
          name: groupname
          schema:
            type: string
            nullable: true
      responses:
        '200':
          description: Successful response

    post:
      summary: Create a new report
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                message:
                  type: string
                  nullable: true
                imageURL:
                  type: string
                  nullable: true
              required:
                - username
      responses:
        '201':
          description: Report created successfully
